<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Unity/Assets/SLR/Domain/*.cs" />
    <Compile Include="../Unity/Assets/SLR/Tests/EditMode/DomainChecks.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
